// src/react/App.js
import React from 'react';
import { HorizontalScreen, SwipeWrap, event } from "./src/index.js"
// import {HorizontalScreen,SwipeWrap,event} from "react-horizontal-screen"
// import {HorizontalScreen,SwipeWrap,event} from "react-xx"
event();
export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      hsObj: {
        width: 2001,
        height: 1125,
        cssVar: "hc-var",
        times: 3
      },
      domSwipeText: "",
      domSwipeText2: "",
    };
    this.myRef = React.createRef();
  }
  swipeCallBack(data, el) {
    let { type, dis } = data;
    console.log("dom event", data, type, dis, el);
    if (type === "swipeLeft" && dis >= 20) {
      this.setState({ "domSwipeText": "swipeLeft" })
      console.log("swipeLeft");
    } else if (type === "swipeRight" && dis >= 20) {
      console.log("swipeRight");
      this.setState({ "domSwipeText": "swipeRight" })
    }
  }
  swipeCallBack2(data, el) {
    let { type, dis } = data;
    console.log("dom event", data, type, dis, el);

    if (type == "swipeBottom" && dis >= 5) {
      console.log("swipeBottom");
      this.setState({ "domSwipeText2": "swipeBottom" })
    } else if (type == "swipeTop" && dis >= 5) {
      this.setState({ "domSwipeText2": "swipeTip" })
    }
  }
  swipeCallback(obj) {
    if (obj.data.data.type) {
      alert(obj.data.data.type);
    } else {
      clearTimeout(window.hsAdaptTimer);
      window.hsAdaptTimer = setTimeout(() => {
        alert('hsAdapt');
      }, 1000)
    }
  }
  adaptedCallback() {
    clearTimeout(window.hsAdaptTimer);
    window.hsAdaptTimer = setTimeout(() => {
      alert('hsAdapt');
    }, 1000)
  }

  render() {
    return (
      <div className="App">
        <HorizontalScreen
          attrs={this.state.hsObj}
          adaptedCallback={this.adaptedCallback}
          className="box">
          <div id="wrap">
            <div className="header">
              <div className="left">25</div>
              <div className="mid">40</div>
              <div className="right">50</div>
            </div>
            <div className="main">
              <SwipeWrap
                swipeCallBack={(data, el) => this.swipeCallBack(data, el)}
                stop={true}
                prevent={true}
                className="dom-event">
                <div className="dom-event">
                  <p>Horizontal sliding area.</p>
                  <h3>swipe type:{this.state.domSwipeText}</h3>
                </div>
              </SwipeWrap>

              <SwipeWrap
                swipeCallBack={(data, el) => this.swipeCallBack2(data, el)}
                stop={true}
                prevent={true}
                className="dom-event">
                <div className="dom-event2">
                  <p>Vertical sliding area.</p>
                  <h3>swipe type:{this.state.domSwipeText2}</h3>
                </div>
              </SwipeWrap>
            </div>
            <div className="footer"></div>
          </div>

        </HorizontalScreen>
      </div>
    );
  }

}

// src/App.vue
<template>
  <div id="app" @click="reset">
    <!-- <div
      v-horizontal-screen="obj"
      class="box"
      ref="hscreen"
      v-if="show2"
      @click="show2 = false"
    >
      <div id="wrap">
        <div class="header">
          <div class="left">25</div>
          <div class="mid">40</div>
          <div class="right">50</div>
        </div>
        <div class="main">
          <div v-hs-swipe.stop.prevent="hsSwipe" class="dom-event">
            <p>Red block is Dom Swipe area.</p>
            <h3>swipe type:{{ domSwipe }}</h3>
          </div>
          <p>window swipe area</p>
        </div>
        <div class="footer"></div>
      </div>
    </div> -->
    <div v-horizontal-screen="obj" class="box" ref="hscreen">
      <div id="wrap">
        <div class="header">
          <div class="left">25</div>
          <div class="mid">40</div>
          <div class="right">50</div>
        </div>
        <div class="main">
          <div v-hs-swipe.stop.prevent="hsSwipe" class="dom-event">
            <p>Red block is Dom Swipe area.</p>
            <h3>swipe type:{{ domSwipe }}</h3>
          </div>
          <p>window swipe area</p>
        </div>
        <div class="footer"></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      obj: {
        width: 2001,
        height: 1125,
        cssVar: "hc-var",
        times: 3,
        disabledresized: false, //removed after v0.1.7
        AdaptEventName: "", //Monitor adaptation status events，default is hsAdapt
        setWrapAttr: false,
      },
      domSwipe: "--",
      show2: true,
    };
  },
  mounted() {
    window.addEventListener("hsAdapt", this.swipeCallback);
    window.addEventListener("swipeLeft", this.swipeCallback);
    window.addEventListener("swipeRight", this.swipeCallback);
    window.addEventListener("swipeTop", this.swipeCallback);
    window.addEventListener("swipeBottom", this.swipeCallback);
  },
  beforeUnmount() {
    /*don't forget to remove eventlistener!!*/
    window.removeEventListener("hsAdapt", this.swipeCallback);
    window.removeEventListener("swipeLeft", this.swipeCallback);
    window.removeEventListener("swipeRight", this.swipeCallback);
    window.removeEventListener("swipeTop", this.swipeCallback);
    window.removeEventListener("swipeBottom", this.swipeCallback);
  },
  methods: {
    swipeCallback(obj) {
      if (obj.data.data.type) {
        alert(obj.data.data.type);
      } else {
        alert("hsAdapt");
      }
    },
    reset() {
      // this.$refs["hscreen"].$hsLayout();
    },
    hsSwipe(data, el) {
      let { type, dis } = data;
      console.log("dom event", data, type, dis, el);
      if (type == "swipeLeft" && dis >= 20) {
        this.domSwipe = "swipeLeft";
        console.log("swipeLeft");
      } else if (type == "swipeRight" && dis >= 20) {
        console.log("swipeRight");
        this.domSwipe = "swipeRight";
      }
      // if (type == "swipeBottom" && dis >= 5) {
      //   console.log("swipeBottom");
      //   this.domSwipe = "swipeBottom";
      // } else if (type == "swipeTop" && dis >= 5) {
      //   console.log("swipeTop");
      //   this.domSwipe = "swipeTop";
      // }
    },
  },
};
</script>

<style lang="scss">
* {
  margin: 0;
  padding: 0;
}

html,
body,
#app {
  width: 100%;
  height: 100%;
  overflow: hidden;
  touch-action: none; /**disabled browser native event */
}
@function px($num) {
  @return calc((#{$num}/ 3 * var(--hc-var)) * 1px);
}
.box {
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background: #fff;
  word-wrap: break-word;
  width: 100%;
  height: 100%;
}
#wrap {
  width: px(667 * 3);
  height: px(375 * 3);
}
p {
  font-size: px(16 * 3);
  text-align: center;
  line-height: 1.4;
}
.header {
  height: px(50 * 3);
  background: goldenrod;
  display: flex;
  color: red;
  .left {
    background: pink;
    height: px(25 * 3);
    width: px(300 * 3);
  }
  .mid {
    background: yellow;
    height: px(40 * 3);
    width: px(300 * 3);
  }
  .right {
    background: black;
    height: px(50 * 3);
    width: px(75 * 3);
  }
}
.main {
  height: px(275 * 3);
  background: green;
  display: flex;
  flex-direction: column;
}
.dom-event {
  height: 50%;
  background: red;
  color: #fff;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
.footer {
  height: px(50 * 3);
  background: blue;
}
</style>
